### ISSUE TITLE
Version of NS3 for this patch

### ISSUE THREAD

**Issue by wallanoo** [Vivek-anand-jain/Reproduce-TCP-BBR-in-ns-3#5]
Hi,

which version of NS3 can be used for this patch? i.e. 3.31?

Can I add it to the mmwave version of Zorzi/Polese in order to run some performance comparisons under 5G?
https://github.com/nyuwireless-unipd/ns3-mmwave

thanks for all in advance,

Ric

**Comment by Vivek-anand-jain** [comment]
Hi Ric,

This work is done somewhere for ns-3.27. Since then, the ns-3 TCP has changed a lot so you cannot use it directly on the latest version.

I am not sure about the mmwave module version and its compatibility with BBR code. You can try copying the mmwave module in repository and check if it works.

Thanks,
Vivek Jain
